version: 2.1
workflows:
  version: 2
  test:
    jobs:
      - python-39
      - python-310
      - python-311
      - python-312
jobs:
  python-39: &test-template
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "/home/circleci/.pyenv/version" }}-{{ checksum "setup.py" }}
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -e .[dev]
      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "/home/circleci/.pyenv/version" }}-{{ checksum "setup.py" }}
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml --flake8 --cov --cov-report=xml:test-reports/coverage.xml pyehm
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - run:
          name: Upload Coverage Results
          command: |
            bash <(curl -s https://codecov.io/bash) \
              -f test-reports/coverage.xml \
              -F unittests \
              -n ${CIRCLE_BUILD_NUM}
    resource_class: large
  python-310:
    <<: *test-template
    docker:
      - image: cimg/python:3.10
  python-311:
    <<: *test-template
    docker:
      - image: cimg/python:3.11
  python-312:
    <<: *test-template
    docker:
      - image: cimg/python:3.12